version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: figurdle
      POSTGRES_USER: figurdle
      POSTGRES_PASSWORD: figurdle_dev_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U figurdle"]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    build:
      context: ../../apps/api
      dockerfile: ../../infra/docker/Dockerfile.api
    environment:
      - DATABASE_URL=postgresql://figurdle:figurdle_dev_password@db:5432/figurdle
      - ENVIRONMENT=development
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../../apps/api:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload

  web:
    build:
      context: ../../apps/web
      dockerfile: ../../infra/docker/Dockerfile.web
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ../../apps/web:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:
