"""Add used_characters table for complete duplicate prevention

Revision ID: 49de2518eed3
Revises: 7fe510ed5153
Create Date: 2025-09-19 00:50:56.738036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49de2518eed3'
down_revision: Union[str, None] = '7fe510ed5153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used_characters',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('character_name', sa.Text(), nullable=False),
    sa.Column('puzzle_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_name', name='unique_character_name')
    )
    op.create_index(op.f('ix_used_characters_character_name'), 'used_characters', ['character_name'], unique=False)
    op.create_index(op.f('ix_used_characters_puzzle_date'), 'used_characters', ['puzzle_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_used_characters_puzzle_date'), table_name='used_characters')
    op.drop_index(op.f('ix_used_characters_character_name'), table_name='used_characters')
    op.drop_table('used_characters')
    # ### end Alembic commands ###
