"""Add image_url to puzzles table

Revision ID: 78ad1d273060
Revises: 49de2518eed3
Create Date: 2025-10-03 01:08:32.411881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78ad1d273060'
down_revision: Union[str, None] = '49de2518eed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzles', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzles', 'image_url')
    # ### end Alembic commands ###
